### ISSUE TITLE
Make a 404 page

### ISSUE THREAD

**Issue by gwennlbh** [gwennlbh/portfolio-v6#78]

**Comment by code-reaper08** [comment]
Hello ! 
I am a beginner starting out and reaching people for contributions so that i can learn and experience.
Would you mind assigning this to me ?
I would be pleased to help.

**Comment by gwennlbh** [comment]
Glad that you stumbled upon my humble repos! Unfortunately, [I already finished that page](https://en.ewen.works/404), just forgot to close the issue somehow. Depending on what you want to learn through contributions, I'll gladly redirect you to one of my other projects; this one is less open to contributions because most of the decisions are design-based, and thus subjective. (note that I said "less" but not "not", if you found bugs, you're welcome to contribute!)

**Comment by code-reaper08** [comment]
Thanks for your kind reply. 
Redirect to some other project of your's when free.

Have a nice day !
